services:

  docplanner-task:
    build:
      context: .
      target: development
      args:
        USER_ID: 1000 # Your user ID
        GROUP_ID: 1000 # Your user ID
    container_name: docplanner-task
    hostname: docplanner-task
    environment:
      PHP_DATE_TIMEZONE: 'Europe/Madrid'
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - '${FORWARD_APP_PORT:-5000}:8080'
    networks:
      - local
    restart: unless-stopped

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-5200}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'database:/var/lib/mysql'
    networks:
      - local
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    restart: unless-stopped

networks:
  local:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './_db_volume_data'
